#!/bin/bash
pasm -b /home/debian/SGK_PDA/Code/PRU/PRU0.p
sleep .1
pasm -b /home/debian/SGK_PDA/Code/PRU/PRU1.p
sleep .1
mv PRU0.bin /home/debian/SGK_PDA/Code/PRU/
sleep .1
mv PRU1.bin /home/debian/SGK_PDA/Code/PRU/
sleep .1
